name: Android CI

on:
  push:
    branches:
      - "master"
      - "kotlin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build App with Gradle
        run: ./gradlew assembleDebug
      - name: Testing app
        run: ./gradlew assembleDebug lint testDebugUnitTest -p app
      - name: Upload Testing app
        uses: actions/upload-artifact@v1
        with:
          name: app-test
          path: app/build/reports/tests/testDebugUnitTest
      